### PR TITLE
initial 1.1

### PR DESCRIPTION
**Pull request by cbouss**
Changes:
- initial release
- keeping as noarch. It will be used as a test dependency.

https://github.com/data-apis/array-api-strict/tree/1.1

### CODE REVIEW

**Review by danpetry — APPROVED** [review]
Well, it would be better to do `skip: True # [py<39]`. but doesn't matter really

**Comment by cbouss** [comment]
> Well, it would be better to do `skip: True # [py<39]`. but doesn't matter really

Because I left it noarch, the constraint is needed in the run section as only one package is produced.

**Comment by danpetry** [comment]
Ah. Thanks

**Comment by danpetry** [comment]
ah. thanks

**Pull request merged**
